// Generated by gencpp from file chatbot_pkg/chatbotRequest.msg
// DO NOT EDIT!


#ifndef CHATBOT_PKG_MESSAGE_CHATBOTREQUEST_H
#define CHATBOT_PKG_MESSAGE_CHATBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chatbot_pkg
{
template <class ContainerAllocator>
struct chatbotRequest_
{
  typedef chatbotRequest_<ContainerAllocator> Type;

  chatbotRequest_()
    : question()
    , answer()  {
    }
  chatbotRequest_(const ContainerAllocator& _alloc)
    : question(_alloc)
    , answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _question_type;
  _question_type question;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct chatbotRequest_

typedef ::chatbot_pkg::chatbotRequest_<std::allocator<void> > chatbotRequest;

typedef boost::shared_ptr< ::chatbot_pkg::chatbotRequest > chatbotRequestPtr;
typedef boost::shared_ptr< ::chatbot_pkg::chatbotRequest const> chatbotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chatbot_pkg::chatbotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chatbot_pkg::chatbotRequest_<ContainerAllocator1> & lhs, const ::chatbot_pkg::chatbotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.question == rhs.question &&
    lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chatbot_pkg::chatbotRequest_<ContainerAllocator1> & lhs, const ::chatbot_pkg::chatbotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chatbot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a27d8629aeefd2b315942fe4a74ab143";
  }

  static const char* value(const ::chatbot_pkg::chatbotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa27d8629aeefd2b3ULL;
  static const uint64_t static_value2 = 0x15942fe4a74ab143ULL;
};

template<class ContainerAllocator>
struct DataType< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chatbot_pkg/chatbotRequest";
  }

  static const char* value(const ::chatbot_pkg::chatbotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string question\n"
"string answer\n"
;
  }

  static const char* value(const ::chatbot_pkg::chatbotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.question);
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chatbotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chatbot_pkg::chatbotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chatbot_pkg::chatbotRequest_<ContainerAllocator>& v)
  {
    s << indent << "question: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.question);
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHATBOT_PKG_MESSAGE_CHATBOTREQUEST_H
