// Generated by gencpp from file chatbot_pkg/chatbotResponse.msg
// DO NOT EDIT!


#ifndef CHATBOT_PKG_MESSAGE_CHATBOTRESPONSE_H
#define CHATBOT_PKG_MESSAGE_CHATBOTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chatbot_pkg
{
template <class ContainerAllocator>
struct chatbotResponse_
{
  typedef chatbotResponse_<ContainerAllocator> Type;

  chatbotResponse_()
    {
    }
  chatbotResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct chatbotResponse_

typedef ::chatbot_pkg::chatbotResponse_<std::allocator<void> > chatbotResponse;

typedef boost::shared_ptr< ::chatbot_pkg::chatbotResponse > chatbotResponsePtr;
typedef boost::shared_ptr< ::chatbot_pkg::chatbotResponse const> chatbotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chatbot_pkg::chatbotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace chatbot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chatbot_pkg::chatbotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chatbot_pkg/chatbotResponse";
  }

  static const char* value(const ::chatbot_pkg::chatbotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::chatbot_pkg::chatbotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chatbotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chatbot_pkg::chatbotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::chatbot_pkg::chatbotResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CHATBOT_PKG_MESSAGE_CHATBOTRESPONSE_H
