// Generated by gencpp from file chatbot_pkg/chatbot.msg
// DO NOT EDIT!


#ifndef CHATBOT_PKG_MESSAGE_CHATBOT_H
#define CHATBOT_PKG_MESSAGE_CHATBOT_H

#include <ros/service_traits.h>


#include <chatbot_pkg/chatbotRequest.h>
#include <chatbot_pkg/chatbotResponse.h>


namespace chatbot_pkg
{

struct chatbot
{

typedef chatbotRequest Request;
typedef chatbotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct chatbot
} // namespace chatbot_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chatbot_pkg::chatbot > {
  static const char* value()
  {
    return "a27d8629aeefd2b315942fe4a74ab143";
  }

  static const char* value(const ::chatbot_pkg::chatbot&) { return value(); }
};

template<>
struct DataType< ::chatbot_pkg::chatbot > {
  static const char* value()
  {
    return "chatbot_pkg/chatbot";
  }

  static const char* value(const ::chatbot_pkg::chatbot&) { return value(); }
};


// service_traits::MD5Sum< ::chatbot_pkg::chatbotRequest> should match
// service_traits::MD5Sum< ::chatbot_pkg::chatbot >
template<>
struct MD5Sum< ::chatbot_pkg::chatbotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot_pkg::chatbot >::value();
  }
  static const char* value(const ::chatbot_pkg::chatbotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot_pkg::chatbotRequest> should match
// service_traits::DataType< ::chatbot_pkg::chatbot >
template<>
struct DataType< ::chatbot_pkg::chatbotRequest>
{
  static const char* value()
  {
    return DataType< ::chatbot_pkg::chatbot >::value();
  }
  static const char* value(const ::chatbot_pkg::chatbotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chatbot_pkg::chatbotResponse> should match
// service_traits::MD5Sum< ::chatbot_pkg::chatbot >
template<>
struct MD5Sum< ::chatbot_pkg::chatbotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chatbot_pkg::chatbot >::value();
  }
  static const char* value(const ::chatbot_pkg::chatbotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chatbot_pkg::chatbotResponse> should match
// service_traits::DataType< ::chatbot_pkg::chatbot >
template<>
struct DataType< ::chatbot_pkg::chatbotResponse>
{
  static const char* value()
  {
    return DataType< ::chatbot_pkg::chatbot >::value();
  }
  static const char* value(const ::chatbot_pkg::chatbotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHATBOT_PKG_MESSAGE_CHATBOT_H
